spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:h2:mem:identity
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/