spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: competence-service-route
          uri: http://localhost:8001
          predicates:
            - Path=/api/v1/competence/**
          filters:
            - AuthenticationJwtFilter

        - id: skill-service-route
          uri: lb://skill-service
          predicates:
            - Path=/api/v1/skills/**\
          filters:
            - AuthenticationJwtFilter

        - id: language-service-route
          uri: lb://language-service
          predicates:
            - Path=/api/v1/languages/**
          filters:
            - AuthenticationJwtFilter

        - id: identity-service-route
          uri: lb://identity-service
          predicates:
            - Path=/api/v1/auth/**

server:
  port: 8005

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true