spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: competence-service-route
          uri: http://localhost:8001
          predicates:
            - Path=/api/v1/competence/**

        - id: skill-service-route
          uri: lb://skill-service
          predicates:
            - Path=/api/v1/skills/**

        - id: language-service-route
          uri: lb://language-service
          predicates:
            - Path=/api/v1/languages/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/micro
server:
  port: 8005

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true