spring:
  application:
    name: competence-service
  datasource:
    url: jdbc:h2:mem:competence
    driver-class-name: org.h2.Driver
    username: sa
    password:
    sql:
      init:
        mode: always
        schema-locations: classpath:schema.sql
    jpa:
      hibernate:
        ddl-auto: none
  logging:
    level:
      org:
        springframework: DEBUG
        hibernate: DEBUG

server:
  port:8001