CREATE TABLE cv
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid VARCHAR(255) NOT NULL,
    CONSTRAINT pk_cv PRIMARY KEY (id)
);

CREATE TABLE cv_languages
(
    cvs_id       BIGINT NOT NULL,
    languages_id BIGINT NOT NULL
);

CREATE TABLE cv_skills
(
    cvs_id    BIGINT NOT NULL,
    skills_id BIGINT NOT NULL
);

CREATE TABLE language
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_language PRIMARY KEY (id)
);

CREATE TABLE skill
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_skill PRIMARY KEY (id)
);

ALTER TABLE cv_skills
    ADD CONSTRAINT fk_cv_skills_on_cv FOREIGN KEY (cvs_id) REFERENCES cv (id);

ALTER TABLE cv_skills
    ADD CONSTRAINT fk_cv_skills_on_skill FOREIGN KEY (skills_id) REFERENCES skill (id);

ALTER TABLE cv_languages
    ADD CONSTRAINT fk_cvlan_on_cv FOREIGN KEY (cvs_id) REFERENCES cv (id);

ALTER TABLE cv_languages
    ADD CONSTRAINT fk_cvlan_on_language FOREIGN KEY (languages_id) REFERENCES language (id);